### ISSUE TITLE
Export static values returned by library

### ISSUE THREAD

**Issue by johntalton** [fivdi/onoff#100]
Export the values of Zero and One used by this library as part of its public interface.

this simplifies consumers of the lib as they can test against the constant values (future proofing? and disambiguating between possible mistakes like "1" vs 1)

see pull request #99

**Comment by johntalton** [comment]
see PR #99

**Comment by fivdi** [comment]
@johntalton Thank you for your work on the pull request for this feature :+1:

onoff@3.1.0 which has just been published on npm now has two new static properties called [HIGH and LOW](https://github.com/fivdi/onoff#static-high--low) which can be in place of the numeric constants 1 and 0.
