### ISSUE TITLE
PWM features.

### ISSUE THREAD

**Issue by jaminbenuk** [fivdi/onoff#11]
Hi,

Firstly I'm loving On/Off... for me it works the best out of all the others that I tried.

Is there any chance you can add PWM features... I was looking at Webiopi and they use PWM ratio and PWM angle and was wondering if it was something you would be able to add.

Many Thanks

**Comment by sebastiaanluca** [comment]
@fivdi Haven't changed your mind yet? :p Trying out pi-blaster, but would be great to have it all in one package.

**Comment by fivdi** [comment]
@sebastiaanluca I didn't change my mind. However, [pigpio](https://github.com/fivdi/pigpio) is very likely to be exactly what your looking for.

**Comment by sebastiaanluca** [comment]
Ooh, neat! Didn't find that through Google, thanks.
