### ISSUE TITLE
Question: How to use in React.JS or Vue.JS 

### ISSUE THREAD

**Issue by aminjoharinia** [fivdi/onoff#120]
Hi 
Is it Possible to import and use in react.js or vue.js
I imported them but got errors,i do not know how exactly do that
i use raspberry pi 3
could you give me examples?
Thanks a Lot

**Comment by fivdi** [comment]
onoff can't be run in a browser as it relies on features that are only available in Node.js. One option here would be to implement a Web application where the Web server is implemented in Node.js and can access GPIOs using onoff. The Web applications front-end would use React or Vue.js.
