### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by Silas007** [fivdi/onoff#124]
Hello,

I can't get the examples to work. I cloned the repository, run 'npm install' switched to examples folder and tried 'node blink-led.js'. I get the error above.

node -v => 10.3.0
npm -v => 6.7.0

I think this is because of epoll. Installed is epoll@2.0.4

Any ideas how to fix this?

UPDATE: I ran the same procedure on my raspberry, not on my OSX. It showed another error (Node-Module-Version conflict) that I could fix by using node v8.15.0

Is this supposed to only run on raspberry and not on other linux systems at all?

Best regards,
Jan

**Comment by fivdi** [comment]
onoff will not install and run correctly on OS X.

> I ran the same procedure on my raspberry, not on my OSX. It showed another error (Node-Module-Version conflict) that I could fix by using node v8.15.0

The most likely cause of this error is that onoff (and therefore epoll) were installed with one version of Node.js, for example, with Node.js v8.x, and an attempt was made to use a different version of Node.js at runtime, for example, Node.js v10.x. epoll is a native Node.js module. When working with native modules the same NODE_MODULE_VERSION must be used at install time and at runtime. The NODE_MODULE_VERSION numbers for the various versions of Node.js can be seen at https://nodejs.org/en/download/releases/

> Is this supposed to only run on raspberry and not on other Linux systems at all?

onoff will run on any Linux system. For example, I've used it on the Raspberry Pi, BeagleBone Black, C.H.I.P and Intel Edison.
