### ISSUE TITLE
FR: promise support

### ISSUE THREAD

**Issue by mbrevda** [fivdi/onoff#127]
Instead of a callback, returning a promises would be nice

**Comment by fivdi** [comment]
I guess promise support would be nice. It would be possible for the asynchronous `read` and `write` methods to support promises but the asynchronous `watch` method couldn't as `watch` can invoke the callback multiple times.

callback support can't be removed as it's needed for existing code.

@mbrevda would you be interested in creating a PR for this feature?

**Comment by fivdi** [comment]
onoff v4.0.0 with Promise support has just been publish on npm.

@saenglert Thank you for the PR which adds this support.

**Comment by mbrevda** [comment]
Thanks!
