### ISSUE TITLE
Don't set direction twice

### ISSUE THREAD

**Issue by benwaffle** [fivdi/onoff#147]
If `direction` is `out`, and `value` is 1, and you run `echo out > direction`, `value` is reset to 0. The constructor for `Gpio` should check if the direction actually needs to be written.

**Comment by fivdi** [comment]
As mentioned in the readme, this can be achieved by setting the [constructors](https://github.com/fivdi/onoff#gpiogpio-direction--edge--options) `reconfigureDirection` option to false.

**Comment by benwaffle** [comment]
Also turns out I can use `high` and `low` in the direction field to atomically set the direction and value

**Comment by fivdi** [comment]
> Also turns out I can use high and low in the direction field to atomically set the direction and value (Linux does this).

Correct. This is also mentioned in the readme.
