### ISSUE TITLE
How to unit-test onoff?

### ISSUE THREAD

**Issue by Triplecorpse** [fivdi/onoff#160]
I want to develop on my PC and then transfer to the board using git.
But I don't have pins on my PC. Is there any guide or recommendations how to test my program without the board?

**Comment by fivdi** [comment]
The [Check accessibility](https://github.com/fivdi/onoff#check-accessibility) section of the readme discusses this topic. See also the [static accessible](https://github.com/fivdi/onoff#static-accessible) property.
