### ISSUE TITLE
"EACCES: permission denied, open '/sys/class/gpio/gpio19/value'" on npm start

### ISSUE THREAD

**Issue by bmwertman** [fivdi/onoff#161]
I have a program that I wrote and successfully ran on a Raspberry Pi 2 B v1.1 I'm now trying to port that over to a Banana Pi M64 for the additional RAM so I don't have to throttle Node's memory usage.

When I start my program I get the error;
`EACCES: permission denied, open '/sys/class/gpio/gpio19/value'
```
const raspi = require('raspi') // https://github.com/nebrius/raspi
const Gpio = require('onoff').Gpio // https://github.com/fivdi/onoff+
const opticSensorA = new Gpio(19, 'in', 'both', { debounceTimeout: 200 })
```
The error is originating from the opticSensorA constant declaration.
Full error message:
```
Unable to parse revision information in /proc/cpuinfo
Unknown board revision , assuming Raspberry Pi Zero/2/3 pinout. Unless you are running a compute module or very old RPi this should work fine. Please report this board revision in a GitHub issue at https://github.com/nebrius/raspi-board.
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES: permission denied, open '/sys/class/gpio/export'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at new Gpio (/home/pi/reefbuddy-server/node_modules/onoff/onoff.js:96:10)
    at Object.<anonymous> (/home/pi/reefbuddy-server/reefbuddy.js:9:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```
OS: Debian 9(Stretch)
Node version: 8.16.1
Board: http://www.banana-pi.org/m64.html

**Comment by fivdi** [comment]
The program ran successfully on the Raspberry Pi because the user that ran the program (presumably user `pi`) had the permissions required to access GPIOs using the sysfs files located at `/sys/class/gpio`. The user running the program on the Banana Pi doesn't have the required permissions. This results in EACCES errors indicating that permission is denied on the Banana Pi.

This isn't actually an onoff issue, it's a Linux permissions issue.

There are two options here.

1. Use `sudo` on the Banana Pi to to run the node program with root privileges. 
2. Give the user that wants to run the node program that accesses the GPIOs the permissions required to access those GPIOs. I'm not familiar with the Banana Pi and don't know what needs to be done to achieve this.

**Comment by bmwertman** [comment]
Thanks @fivdi that's what I've found as I've continued to investigate today. 

It seems some have been able to add a file to their `udev` directory that has a `.rules` extension and calls `chmod` and `chown` to allow the access to the gpio.

I tried that but I'm not sure of how to name the `.rules` file to get Linux to see it.

For me running `sudo npm start` fails with `sudo: npm: command not found`.

**Comment by fivdi** [comment]
> I tried that but I'm not sure of how to name the .rules file to get Linux to see it.

On the Raspberry Pi the file is called `/etc/udev/rules.d/99-com.rules` but to the best of my knowledge it doesn't matter what the file is called.

> For me running `sudo npm start` fails with `sudo: npm: command not found`.

does the following work:
```
sudo $(which npm) start
```
or does this work:
```
sudo $(which node) your-app-name.js
```

**Comment by bmwertman** [comment]
`99-com.rules` is what I named my file, that is the path that it is at and the one liner I have there is;
```
SUBSYSTEM=="gpio", PROGRAM="/bin/sh -c 'find -L /sys/class/gpio/ -maxdepth 2 -exec chown root:gpio {} \; exec chmod 770 {} \; || true'"
```
running the last two sudo commands you just gave both resulted in;

`/usr/bin/env: 'node': No such file or directory`

**Comment by fivdi** [comment]
As mentioned above, I'm afraid I don't know what needs to be done on a Banana Pi to give a normal user access to GPIOs.

>running the last two sudo commands you just gave both resulted in;
>
>/usr/bin/env: 'node': No such file or directory

It looks like node is not installed in a way that makes it usable for user `root`.

**Comment by bmwertman** [comment]
This [SO post answer](https://stackoverflow.com/a/38734497/2041665) seemed to fix the Nodejs issue and I'm getting some different errors now that tell me that the sudo commands seem to have fixed the permission issue I was having. 

Not ideal but it at least gets me moving forward until I can get a more permanent fix in place. 

Thanks for the help!

**Comment by fivdi** [comment]
You're welcome. Have fun with onoff.
