### ISSUE TITLE
Add support for remote GPIO

### ISSUE THREAD

**Issue by Sawtaytoes** [fivdi/onoff#163]
Raspberry Pi supports Remote GPIO.

![image](https://user-images.githubusercontent.com/3948069/70111236-3788ea00-1617-11ea-9517-216ecfc04f71.png)

It'd be great if I could run `onoff` on my development machine and pass in the hostname of the Raspberry Pi device to remotely access the values on the GPIO pins without having to test my software on the machine itself.

**Comment by fivdi** [comment]
The "Remote GPIO" option in the screenshot above is only related to GPIO Zero and pigpio. It's not a general option that will activate remote GPIO for all tools and libraries. As such, it will not enable remote GPIO for onoff.

See https://gpiozero.readthedocs.io/en/stable/remote_gpio.html

Remote GPIO is outside the scope of onoff. You could however implement a server on the Pi which controls GPIOs on the Pi and then communicate with the server on the Pi from your development machine.

**Comment by Sawtaytoes** [comment]
About exposing GPIO myself, that's what I've ended up doing. I was hoping to reduce the custom software load on my remote Pis, but I guess that's not possible.

Thanks for going into detail about Remote GPIO. Documentation on it is confusing for someone who's not in-the-know. Even seeing your response. I have no clue what GPIO Zero and pigpio are or how they're related, but after looking them up, it's clear Remote GPIO is designed for a completely different use case to what onoff is solving.
