### ISSUE TITLE
Read pin always returning to 0 in both sync and async

### ISSUE THREAD

**Issue by apvenkat** [fivdi/onoff#169]
I am using express, node js and onoff module. When I make a PUT request with led.write(value), the satus of LED is changing. After that when I execute a GET request to led.readsync() it is always turning off the LED and returns 0 ?? Any suggestions ??

**Comment by fivdi** [comment]
If I had to guess I'd say that each GET request is creating a new Gpio object and when that new object is created, the LED is being turned off automatically. The PUT and GET requests should be using the same Gpio object.

**Comment by fivdi** [comment]
There doesn't appear to be a TODO for onoff here so I'll go ahead and close the issue.
