### ISSUE TITLE
Ability to configure pullup/pulldown

### ISSUE THREAD

**Issue by thexperiments** [fivdi/onoff#18]
would be great if one could configure pullup/pulldown for the ports via the api

**Comment by fivdi** [comment]
@fireblade983 sorry for the delay, I somehow missed your post.

Here's how to configure pullup/down resistors using the WiringPi gpio utility.
First, install WiringPi as described [here](http://wiringpi.com/download-and-install/).
After a successful install, the gpio utility will be available. It's described [here](http://wiringpi.com/the-gpio-utility/).

Lets say you want to configure the pulldown resistor on GPIO8. This can be acheived with the following command sequence:

```bash
pi@raspberrypi ~ $ gpio -g mode 8 down
pi@raspberrypi ~ $ 
```
If nothing is wired up to GPIO8, reading it's value should return 0. To see this cd into `/sys/class/gpio` try the following:

```
pi@raspberrypi /sys/class/gpio $ echo 8 > export 
pi@raspberrypi /sys/class/gpio $ cat gpio8/value 
0
pi@raspberrypi /sys/class/gpio $ 
```

To configure the pullup resistor on GPIO8:

```
pi@raspberrypi ~ $ gpio -g mode 8 up
pi@raspberrypi ~ $ 
```
If nothing is wired up to GPIO8, reading it's value should return 1. To see this cd into `/sys/class/gpio` try the following:
```
pi@raspberrypi /sys/class/gpio $ cat gpio8/value 
1
pi@raspberrypi /sys/class/gpio $ 
```
So, if you write a bash script to configure the pullup/down resistors the way you want them, and execute this bash script before you start your Node.js program, the pullup/down resistors will be configured as desired.

**Comment by fivdi** [comment]
In the not too distant future Raspbian will support the Linux device tree. When this is the case, onoff should be able to configure pullup/down resistors without requiring additional tools such as WiringPi.

**Comment by fivdi** [comment]
The January 2015 release of Raspbian with Linux kernel 3.18.5 supports the device tree and has it enabled by default. This means that it's now possible to use device tree overlays to configure pullup and pulldown resistors for GPIOs. The onoff Wiki page [Enabling Pullup and Pulldown Resistors on The Raspberry Pi](https://github.com/fivdi/onoff/wiki/Enabling-Pullup-and-Pulldown-Resistors-on-The-Raspberry-Pi) describes how this can be acheived on the Raspberry Pi.

Using device tree overlays to configure pullup and pulldown resistors goes with the grain of how Linux would like things to be done. Device tree overlays are loaded at boot time. There are techniques that can be used to configure pullup and pulldown resistors at runtime, but these generally require root privileges and this is a road that I don't want to go down with onoff.
