### ISSUE TITLE
My computer does not have a /sys/class/gpio directory, but has /dev/gpiochip*

### ISSUE THREAD

**Issue by yueduz** [fivdi/onoff#190]
Hi!
As written in https://embeddedbits.org/new-linux-kernel-gpio-user-space-interface/, my computer does not have the /sys/class/gpio directory, but has /dev/gpiochip*, how can I download Node uses gpio.
thanks

**Comment by fivdi** [comment]
Duplicate of #118 

There are currently no plans to modify onoff to use the new chardev interface for accessing GPIOs.
