### ISSUE TITLE
Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by saiskarur** [fivdi/onoff#193]
Hi, I am facing issue on accesssing Gpio.writeSync, could you please help me out from this.

**Comment by saiskarur** [comment]
![image](https://user-images.githubusercontent.com/700844/168853660-d5406a9d-d297-4f6f-9bb4-caa2d6fa6da1.png)

**Comment by saiskarur** [comment]
its wokring once i use this comment until i am restarting the device

pi@raspberrypi:~ $ cd /sys/class/gpio/
pi@raspberrypi:/sys/class/gpio $ echo 4 > export 
pi@raspberrypi:/sys/class/gpio $ echo out > gpio4/direction 
pi@raspberrypi:/sys/class/gpio $ echo 1 > gpio4/value 
pi@raspberrypi:/sys/class/gpio $

**Comment by fivdi** [comment]
@saiskarur please post a short but complete JavaScript program that can be used to reproduce the problem.

**Comment by fivdi** [comment]
Without haven seen code that can be used to reproduce the error, my best guess is that the program attempted to write to a GPIO that was configured as an input. Input GPIOs can not be written to, only output pins can be written to.

I'll go ahead and close the issue.
