### ISSUE TITLE
Does not work with Compute Module 4.

### ISSUE THREAD

**Issue by SteveC00k** [fivdi/onoff#194]
I have tried multiple times and cannot get this to work with RPI Compute Module 4. (CM4102032)
I am not going to bother placing anything here as there was no errors and it just sat there not even responding to the call back example. 
More work needs to be done for these.

**Comment by fivdi** [comment]
onoff is most likely being used incorrectly. For example, perhaps pin numbers were used rather than GPIO numbers.

**Comment by SteveC00k** [comment]
Actually I tried the BCPM numbers.
Also I was using one of the examples.
So no I did not use it incorrectly.
