### ISSUE TITLE
Superb library - I am running on Node v20 

### ISSUE THREAD

**Issue by r1ch** [fivdi/onoff#196]
Thanks @fivdi (for this + epoll)

 Can I help run tests / contribute a PR for Node v20 coverage

Anecdotally this seems to work perfectly - but let me know if I can help.

**Comment by fivdi** [comment]
Sorry for not responding sooner. All is ok with Node v20 and Node v21 and everything should function as expected. It's just not mentioned in the readme.

**Comment by r1ch** [comment]
Thanks
