### ISSUE TITLE
On which computer do you use onoff?

### ISSUE THREAD

**Issue by fivdi** [fivdi/onoff#28]
I'd be very interested in knowing on which computers people use onoff.

The Raspberry Pi?
The BeagleBone or BeagleBone Black?
Maybe something else?

If you happen to read this and use onoff, I would be very, very grateful if you posted a comment below saying on which computer you use onoff.

**Comment by fivdi** [comment]
The BeagleBone, the BeagleBone Black, and the Raspberry Pi.

**Comment by 8power8** [comment]
Hi Brian, I use onoff mainly on the Raspberry Pi, B and A+ models

**Comment by fivdi** [comment]
@8power8 Thanks for the feedback :+1:

**Comment by fivdi** [comment]
I did a search on github to see which computers were being used. It's the Raspberry Pi most of the time. I guess that was to be expected.
