### ISSUE TITLE
installing onoff hangs/freeze there

### ISSUE THREAD

**Issue by clonez** [fivdi/onoff#34]
installing onoff on raspberry pi 2 model B, NOOBs v1.4.1 seems to hang at the terminal for very long. Is there any resolve in this? Usually install via 'npm install onoff --save'

**Comment by fivdi** [comment]
The first time a module that relies on an addon is installed can take a while, but not extremely long. This is because node-gyp downloads the node tar file. How long is it taking on your system?

**Comment by clonez** [comment]
ah i see...noted. I will try installing it again, thanks
