### ISSUE TITLE
All relays turn on when starting the app

### ISSUE THREAD

**Issue by docmattman** [fivdi/onoff#57]
I'm using onoff to control a relay board with LEDs.  When I start the app script, all LEDs turn on automatically.  Is there a way to prevent onoff from turning all my relays on when initializing them?

**Comment by fivdi** [comment]
The direction argument passed to the [Gpio constructor](https://github.com/fivdi/onoff#gpiogpio-direction--edge--options) is usually `'out'` for an output Gpio. Instead of `'out'`, `'high'` or `'low'` can also be specified and will configure the GPIO as an output with an initial level of high or low respectively.

Can `'high'` or `'low'` be specified to achieve the desired behavior?

**Comment by fivdi** [comment]
@docmattman were you able to make any progress here?

**Comment by danb5** [comment]
This bug makes this unusable.

**Comment by fivdi** [comment]
So calling the Gpio constructor with a direction argument of `'high'` or `'low'` instead of `'out'` didn't help?

**Comment by danb5** [comment]
I must admit to being a novice.  I am trying to use this with a home bridge plugin called homebridge-gpio-garagedoor.  It uses onoff as a dependancy for goop control.   Not sure how I change how onoff sets the pin.

**Comment by danb5** [comment]
Forgot.  I am using a Raspberry Pi zero running Jesse.

**Comment by danb5** [comment]
Where do I call the grip constructor

**Comment by fivdi** [comment]
It looks link it's being called indirectly from here: https://github.com/KraigM/homebridge-gpio-garagedoor/blob/master/lib/SwitchPort.ts#L20

That's TypeScript code so the TypeScript transpiler will need to be called to generate the JavaScript code.

**Comment by danb5** [comment]
Hmm,  I will need to figure out what you mean but I see where you are pointing in the code.  I can't thank you enough for the help.

**Comment by fivdi** [comment]
@docmattman @danb5 were you able to make any progress here?

**Comment by danb5** [comment]
Sorry, yes you were correct in the issue. 

Dan

**Comment by fivdi** [comment]
That's good news. Thanks for the feedback.

**Comment by docmattman** [comment]
Sorry for the late response.  Setting the direction to `high` or `low` did work.  At the time, I wasn't aware those were options.  I only saw `out`.  So, yes, problem solved.  Thanks!

**Comment by fivdi** [comment]
I'm glad it worked and thanks for taking the time to provide the feedback.

**Comment by Cirrostratuss** [comment]
@docmattman where did you change the direction?
