### ISSUE TITLE
Clocking signal

### ISSUE THREAD

**Issue by rogueturnip** [fivdi/onoff#58]
I wanted to find out if onoff would be a good solution for watching a clock signal on a pin.  What I have is a clock that runs for a period of time and a data line that can be read on the clock high and written to on clock low.  After a period of time it goes all high for about 500ms to synchronize and then starts again.

Would onoff be a good option to monitor this clock so I could read or write the data?

Thanks!

**Comment by fivdi** [comment]
What's the frequency of the clock signal during the data transfer phase and what type of computer is being used?

**Comment by rogueturnip** [comment]
I'm hoping to drive this off a beaglebone.  I've attached what a scope shows of the clocking.
![dsc1](https://cloud.githubusercontent.com/assets/7782364/20072955/46aad3f6-a4df-11e6-9343-8a9367d1b5c5.gif)
![dsc2](https://cloud.githubusercontent.com/assets/7782364/20072960/48d9a65c-a4df-11e6-8913-098a5ee85bec.gif)

**Comment by fivdi** [comment]
That looks like a 1KHz clock. There's a reasonable chance that it will work.

**Comment by fivdi** [comment]
@rogueturnip was it possible to watch the clock signal with onoff?

**Comment by fivdi** [comment]
On second thoughts, this is very unlikely to function correctly. A 1KHz clock signal means 2000 state changes per second which in turn implies an interrupt every 500 microseconds. Internally onoff has a thread that calls epoll to detect interrupts. When an interrupt is detected by this thread, the appropriate callback in the JavaScript main thread is called. Given that Linux isn't a realtime operating system interrupts are almost certain to be missed at this rate.
