### ISSUE TITLE
Push only button event

### ISSUE THREAD

**Issue by zafar-saleem** [fivdi/onoff#78]
I want to turn the LED on by pressing the button and then when I want to turn the LED off then I press the button again. That means I do not want to handle the release state. The LED will be on unless I press the button again to turn it off. Currently when I use the "watch" method then it listens to both press and release. The LED is on when I press the button and is off when I release the button. Is there a way to achieve this in onoff?

**Comment by fivdi** [comment]
The `value` argument passed to the watch callback can be used to determine if the button was pressed or released. If `value` is 1 the button was pressed. If `value` is 0 the button was released. So if you're only interested in handling button press events then check to see if `value` is 1 in the watch callback. If it is, the button was pressed.

**Comment by zafar-saleem** [comment]
Great I achieved it using a legacy(but still amazing) logic :).

`let counter = 0;

button.watch((error, value) => {
    if (value === 0 && counter >= 1) {
        led.writeSync(0);
        counter--;
        return;
    }

    if (value === 0 && counter <= 0) {
        led.writeSync(1);
        counter++;
        return;
    }
});`

**Comment by fivdi** [comment]
Ok, good to hear.
