### ISSUE TITLE
Enabling Pullup/Pulldown Programatically?

### ISSUE THREAD

**Issue by wordyallen** [fivdi/onoff#80]
I'm not sure if this is possible, but I  know the python `RPi` package handles it. 

https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/

 something like this would be ideal:

```js
...
button = new Gpio(4, 'in', 'both', 'pulldown');
```

**Comment by fivdi** [comment]
In addition to supporting the Raspberry Pi onoff also supports other platforms like the BeagleBone or C.H.I.P. It other words it supports any Linux system that allows access to GPIOs using the sysfs files located at /sys/class/gpio. There is currently no way to specify how to configure pullup/pulldown resistors using these sysfs files. It's therefore not possible to add this functionality to onoff.

A potential alternative package that does allow pullup/pulldown resistors to be configured programmatically is [pigpio](https://github.com/fivdi/pigpio).
