### ISSUE TITLE
High resolution timestamp as 3rd argument to watch callback?

### ISSUE THREAD

**Issue by davidtinker** [fivdi/onoff#84]
This would be useful when trying to do accurate timing e.g. for calculating distances using a HC-SR04 ultrasonic range sensor. I couldn't get accurate enough timing using JS and process.hrtime().

On a related note, is it possible to watch an output?

Tx for creating onoff.

**Comment by fivdi** [comment]
> High resolution timestamp as 3rd argument to watch callback?
> This would be useful when trying to do accurate timing e.g. for calculating distances using a HC-SR04 ultrasonic range sensor. I couldn't get accurate enough timing using JS and process.hrtime().

The mechanisms used internally by onoff are not suitable enough for determining the time of a GPIO state change accurate to a small number of microseconds. This is what's required for measuring proximity with a HC-SR04. The [pigpio](https://github.com/fivdi/pigpio) module does however have a mechanism called alerts that allows the time of a GPIO state change to be determined accurate to a few microseconds. It works quite well with the HC-SR04 ultrasonic range sensor. There's an example [here](https://github.com/fivdi/pigpio#measure-distance-with-a-hc-sr04-ultrasonic-sensor).

> On a related note, is it possible to watch an output?

As mentioned in the [documentation for the Gpio constructor](https://github.com/fivdi/onoff#gpiogpio-direction--edge--options) the 3.13 Linux kernel dropped support for interrupt generating outputs, irrespective of whether the underlying hardware supports them or not. onoff therefore doesn't support watching outputs.

> Tx for creating onoff.

You're welcome :)

**Comment by fivdi** [comment]
So onoff won't be extended to support such timestamps as the timestamps would not be particularly accurate.
